### ISSUE TITLE
HitBox and AI

### ISSUE THREAD

**Issue by NerfThis123** [2piradians/Minewatch#15]
For some reason when you hit hero mods anywhere but the arms it dose not hit or damage the hero and when you put a hole like in the middle of the map can you make it so that there smart enough not to wall into the hole when battling

**Comment by Furgl** [comment]
Hero mobs do not use any special hit boxes or hit detection - you can see their hit boxes with F3+B. Try leading your shots if you have trouble hitting them.

Hero mobs use vanilla AI for path-finding.
