### ISSUE TITLE
Seismic Slam vs Grass

### ISSUE THREAD

**Issue by HydroPotato5** [2piradians/Minewatch#18]
When I use Doomfist's Seismic Slam (on Minewatch-1.12.X-3.11), the Seismic Slam visual goes through grass (the one you can walk through, not grass block), but entities behind or in the grass do not take slam damage. Also, if I slam onto a block with grass on it, the slam activates on top of the grass, rather than when hitting the block. Help please, this makes fighting things in fields unnecessarily difficult.

**Comment by Furgl** [comment]
Fixed for the next update, thank you for reporting
