### ISSUE TITLE
Qestion/Bug

### ISSUE THREAD

**Issue by NerfThis123** [2piradians/Minewatch#19]
I have the latest version of Minewatch, Minecraft, and Forge and do not have any mods installed
*Mercy's Guardian Angle straight up dose not work even if you look in the direction of your teammate.
*I thought if you kill someone with reaper they drop souls and you pick them up to get healed not just when you shoot them.

**Comment by Furgl** [comment]
Mercy's Guardian Angel not working was reported and is fixed for the next update.
Reaper no longer drops souls in Overwatch and therefore does not in Minewatch.
