### ISSUE TITLE
crash-report client 

### ISSUE THREAD

**Issue by le10077** [2piradians/Minewatch#2]
thank you!
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Chiseled Me ASM (Chiseled-Me-1.0.jar)
  ItemPatchingLoader (ItemPhysic Full 1.4.6 mc1.10.2.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
  CreativePatchingLoader (CreativeCore v1.7.3 mc1.10.2.jar)
  TickrateChanger (TickrateChanger-1.0.8.jar)
  MalisisCorePlugin (MalisisCore.jar)
  SPFMLLoadingPlugin (Sound Physics.jar)
  NWRTweak (Redstone Paste.jar)
  FMLPlugin (MODInventoryTweaks-1.61-58.jar)
  ColorUtilityCorePlugin (ColorUtility.jar)
  LoadingPlugin (Quark.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 11/17/17 7:59 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at twopiradians.minewatch.client.key.Keys.mouseEvents(Keys.java:217)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3_Keys_mouseEvents_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:232)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2205)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1741)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at twopiradians.minewatch.client.key.Keys.mouseEvents(Keys.java:217)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3_Keys_mouseEvents_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:232)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2205)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mushroom'/153, l='MpServer', x=-1325.55, y=4.00, z=-251.18]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1367,4,-231), Chunk: (at 9,0,9 in -86,-15; contains blocks -1376,0,-240 to -1361,255,-225), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Level time: 34189 game time, 34189 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityPigletYorkshire['约克夏猪（小猪）'/1, l='MpServer', x=-1370.55, y=4.00, z=-205.46], EntityItem['item.item.leather'/246272, l='MpServer', x=-1302.85, y=4.00, z=-228.06], EntityEweDorset['Dorset Ewe'/273280, l='MpServer', x=-1350.60, y=4.00, z=-259.00], EntityPlayerSP['Mushroom'/153, l='MpServer', x=-1325.55, y=4.00, z=-251.18], EntityRamDorset['Dorset Ram'/273281, l='MpServer', x=-1349.53, y=4.00, z=-259.33], EntityLambDorset['Dorset Lamb'/273282, l='MpServer', x=-1351.18, y=4.00, z=-259.68], EntitySowYorkshire['约克夏猪（母猪）'/273283, l='MpServer', x=-1349.09, y=4.00, z=-258.36], EntityPigletYorkshire['约克夏猪（小猪）'/273292, l='MpServer', x=-1351.02, y=4.00, z=-257.99], EntityCalfFriesian['黑白花牛（小牛）'/9, l='MpServer', x=-1358.65, y=4.00, z=-268.72], EntityFishClownfish['Clownfish'/10, l='MpServer', x=-1361.68, y=4.13, z=-234.50], EntityFishClownfish['Clownfish'/11, l='MpServer', x=-1361.50, y=4.13, z=-235.50], EntityFishClownfish['Clownfish'/12, l='MpServer', x=-1362.43, y=4.13, z=-235.51], EntityFishClownfish['Clownfish'/13, l='MpServer', x=-1362.47, y=4.13, z=-235.25], EntityFishClownfish['Clownfish'/14, l='MpServer', x=-1362.81, y=4.13, z=-235.71], EntityHogYorkshire['约克夏猪（公猪）'/273291, l='MpServer', x=-1350.19, y=4.00, z=-257.92], EntityItem['item.item.leather'/233875, l='MpServer', x=-1288.84, y=4.00, z=-225.83], EntityHorse['马'/18, l='MpServer', x=-1326.25, y=4.00, z=-252.19], EntitySlime['史莱姆'/198360, l='MpServer', x=-1355.37, y=4.00, z=-218.71], EntitySlime['史莱姆'/246367, l='MpServer', x=-1334.78, y=4.08, z=-213.93], EntitySlime['史莱姆'/257948, l='MpServer', x=-1360.23, y=4.27, z=-265.88], EntityXPOrb['经验球'/269798, l='MpServer', x=-1304.66, y=4.00, z=-249.43], EntityItem['item.item.leather'/268513, l='MpServer', x=-1305.20, y=4.00, z=-249.01], EntitySlime['史莱姆'/253158, l='MpServer', x=-1370.38, y=5.08, z=-274.24], EntityRamDorset['Dorset Ram'/273278, l='MpServer', x=-1352.70, y=4.00, z=-258.71], EntityLambDorset['Dorset Lamb'/273279, l='MpServer', x=-1361.34, y=4.00, z=-259.95], EntityItem['item.item.beefRaw'/246271, l='MpServer', x=-1302.05, y=4.00, z=-228.59], EntityEweDorset['Dorset Ewe'/273272, l='MpServer', x=-1351.55, y=4.00, z=-257.18], EntitySlime['史莱姆'/245182, l='MpServer', x=-1354.41, y=4.00, z=-261.05], EntityRamDorset['Dorset Ram'/273273, l='MpServer', x=-1351.76, y=4.00, z=-258.49], EntityLambDorset['Dorset Lamb'/273274, l='MpServer', x=-1351.39, y=4.00, z=-259.08], EntityEweDorset['Dorset Ewe'/273275, l='MpServer', x=-1352.50, y=4.00, z=-257.35]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1126197856 bytes (1074 MB) / 2621440000 bytes (2500 MB) up to 2621440000 bytes (2500 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2500m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2422 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJAAAA	Forge{12.18.3.2422} [Minecraft Forge] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJAAAA	ColorUtility{1.0.3} [ColorUtility] (minecraft.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCHIJAAAA	animania{1.3.6} [Animania] (animania-1.10.2-1.3.6 (1).jar) 
	UCHIJAAAA	architect{1.1.2.31} [Architect] (architect.jar) 
	UCHIJAAAA	astikoor{1.0.0} [Astikoor] (astikoor-1.0.0.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib.jar) 
	UCHIJAAAA	bamboomod{Minecraft1.10.2 var3.0.0.12.2} [bamboomod] (BambooMod.jar) 
	UCHIJAAAA	chiseled_me{1.0} [Chiseled Me] (Chiseled-Me-1.0.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei.jar) 
	UCHIJAAAA	chiselsandbits{12.12} [Chisels & Bits] (Chisels & Bits.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	creativecore{1.7.4} [CreativeCore] (CreativeCore v1.7.3 mc1.10.2.jar) 
	UCHIJAAAA	modcurrency{1.10.2-1.2.2} [Good Ol' Currency Mod] (Currency-1.10.2-1.2.2.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(22jul17)_test.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (Elevator Mod.jar) 
	UCHIJAAAA	ExtraBitManipulation{1.10.2-2.5.1} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.5.1.jar) 
	UCHIJAAAA	fakename{1.2} [Fake Name] (Fake Name.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5 (2).jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5 (1).jar) 
	UCHIJAAAA	googlyeyes{6.0.0} [GooglyEyes] (GooglyEyes-1.10.2-6.0.0.jar) 
	UCHIJAAAA	hopperducts{1.4.8} [Hopper Ducts] (Hopper Ducts.jar) 
	UCHIJAAAA	incontrol{3.6.0} [InControl] (incontrol-3.6.0.jar) 
	UCHIJAAAA	jaff{1.5.3_for_1.10.2} [Just a Few Fish] (JustAFewFish-1.5.3_for_1.10.2.jar) 
	UCHIJAAAA	malisiscore{1.10.2-4.4.0} [MalisisCore] (MalisisCore.jar) 
	UCHIJAAAA	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (MalisisDoors.jar) 
	UCHIJAAAA	materialchanger{1.0} [Material Changer] (materialchanger1.0-1.10.2 (1).jar) 
	UCHIJAAAA	mtrm{1.2.1.26} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.26.jar) 
	UCHIJAAAA	minewatch{3.5} [Minewatch] (Minewatch-1.10.2-3.5.jar) 
	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJAAAA	placeableitems{3.0.4.1} [Placeable Items Mod] (placeableitems-3.0.4.1 (1).jar) 
	UCHIJAAAA	redstonepaste{1.7.4} [Redstone Paste] (Redstone Paste.jar) 
	UCHIJAAAA	SimilsaxTranstructors{1.10.2.18} [Similsax Transtructors] (Similsax Transtructors.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAAAA	tickratechanger{1.0.8} [Tickrate Changer] (TickrateChanger-1.0.8.jar) 
	UCHIJAAAA	tobymodchest{1.2} [Toby Mod Chest] (Toby Mod Chest.jar) 
	UCHIJAAAA	toolbelt{1.2.1} [Tool Belt] (toolbelt.jar) 
	UCHIJAAAA	worldlimiter{1.0.2} [§bWorld Limiter Mod] (worldlimiter-1.10.2-1.0.2.jar) 
	UCHIJAAAA	friendlyfire{1.3.0} [Friendly Fire] (pet.jar) 
	UCHIJAAAA	hud{1.3.8} [Better HUD] (Better HUD.jar) 
	UCHIJAAAA	blur{1.0.3-13} [Blur] (Blur-1.0.3-13.jar) 
	UCHIJAAAA	chattimestamp{1.0.0} [ChatTimestamp] (ChatTimestamp.jar) 
	UCHIJAAAA	customcrosshairmod{0.5.2-forge} [Custom Crosshair Mod] (Custom Crosshair Mod.jar) 
	UCHIJAAAA	dynamic_lighting{1.3} [Dynamic Lighting] (Dynamic Lighting-1.3.jar) 
	UCHIJAAAA	FpsReducer{1.10.2-1.7} [FPS Reducer] (FpsReducer-1.10.2-1.7.jar) 
	UCHIJAAAA	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
	UCHIJAAAA	IngameAccountSwitcher{7.0.1} [In-Game Account Switcher] (InGameAccountSwitcher-Forge-1.10.2-7.0.1.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	minemenu{1.4.5} [MineMenu] (MineMenu.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (MODInventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	soundphysics{1.0.0} [Sound Physics] (Sound Physics.jar) 
	UCHIJAAAA	torohealthmod{1.10.2-7} [ToroHealth Damage Indicators] (ToroHealth Damage Indicators.jar) 
	UCHIJAAAA	tumat{1.6.0} [TUMAT] (TUMAT-1.6.0.jar) 
	UCHIJAAAA	hotswappablearmor{1.0} [Hot-Swappable Armor] (Hot-Swappable_Armor_v1.0_mc_v1.10.2.jar) 
	UCHIJAAAA	mycommands{1.9.4-1.10.2-05} [MY Commands] (MyCommands-1.9.4-1.10.2-05.jar) 
	Loaded coremods (and transformers): 
Chiseled Me ASM (Chiseled-Me-1.0.jar)
  necauqua.mods.cm.asm.Plugin
ItemPatchingLoader (ItemPhysic Full 1.4.6 mc1.10.2.jar)
  com.creativemd.itemphysic.ItemTransformer
BlurPlugin (客户端Blur-1.0.3-13.jar)
  com.tterrag.blur.BlurTransformer
CreativePatchingLoader (CreativeCore v1.7.3 mc1.10.2.jar)
  
TickrateChanger (TickrateChanger-1.0.8.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
MalisisCorePlugin (MalisisCore.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
SPFMLLoadingPlugin (客户端Sound Physics.jar)
  com.sonicether.soundphysics.SoundPhysicsCore
NWRTweak (Redstone Paste.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (客户端MODInventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ColorUtilityCorePlugin (ColorUtility.jar)
  com.Axeryok.ColorUtility.ColorUtilityTransformer
LoadingPlugin (Quark.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'Quadro K2000M/PCIe/SSE2'
	Launched Version: HMCL 2.5.3.88
	LWJGL: 2.9.4
	OpenGL: Quadro K2000M/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Stardew Valley Music in Minecraft.zip (incompatible), Fanver_Modded_Universal.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz

**Comment by le10077** [comment]
version:1.10.2-forge1.10.2-12.18.3.2422

**Comment by Furgl** [comment]
I remember we fixed this issue a while ago, but we must have accidentally deleted the fix. We’ll have this fixed in the next update, until then you can still use the mod if you avoid triggering it: this issue should be isolated to mc 1.10.2 when you left click with a weapon from the mod in the offhand but not in the mainhand. 

Thank you for reporting it to us!

**Comment by le10077** [comment]
Thanks for your reply. Looking forward to next update
