### ISSUE TITLE
Player cannot shoot or use specials when playing on Server

### ISSUE THREAD

**Issue by dhry** [2piradians/Minewatch#25]
Playing MC 1.12.2, latest server, latest Forge and latest Minewatch mod. When playing singleplayer it all works fine. Play multiplayer on server, and everything works (can see new MW tabs, items etc) except player cannot shoot gun or use special eg grappling hook. Is there a special entry in server.properties that needs to be configured to allow this? Are we doing something wrong?

**Comment by Furgl** [comment]
Sounds like Minewatch isn't installed on the server

**Comment by dhry** [comment]
Absolutely sure it's installed. I ran the Forge installer, installed it to a brand new directory, it downloaded the MC server, installed libraries and the forge jar. Copied in a /mods folder with Minewatch. Started server. Server starts fine. What am I missing?

**Comment by dhry** [comment]
![image](https://user-images.githubusercontent.com/4991066/59481747-5fdb1d00-8e1a-11e9-9795-82c6398df690.png)

**Comment by dhry** [comment]
![image](https://user-images.githubusercontent.com/4991066/59481760-72eded00-8e1a-11e9-9507-15971e3a95e1.png)

**Comment by Furgl** [comment]
Send the full log from starting up the server

**Comment by dhry** [comment]
I figured it out. I was trying to run the server jar directly, which of course starts up the server, but doesn't load forge. Kept doubleclicking on the forge.jar, didn't do a thing. Dropped to a command prompt and ran java -jar forgexxx.jar and lo and behold, it started up the server with mods. Had to go through many Google pages before I found that.

**Comment by Furgl** [comment]
I figured it was something like that, didn't see any mention of FML in the console screenshot. 

Glad you could figure it out.
