### ISSUE TITLE
Nothing working on bukkit server

### ISSUE THREAD

**Issue by TheGoldenAdmin** [2piradians/Minewatch#4]
In singleplayer it goes fine for 1.10.2, but for sp 1.12.2 applies as for my servers. Abbilities and projectiles behave as if they weren't in the game. Gun functionality is fine (Mc Cree's revolver moved up when rapidfiring, Widowmaker's kiss percentage loaded. I'm currently using 1.10.2 Bukkit server (tried 1.12.2 first).
Both had the same issue.

**Comment by Furgl** [comment]
What do you mean by “Abbilities and projectiles behave as if they weren't in the game”? Do they just not appear on clientside (entities are still damaged by invisible bullets) or do they not seem to shoot at all? And are there any errors in the console?

**Comment by TheGoldenAdmin** [comment]
Nothing damaged. Tho it could be incompatibility with jei and journeymap so trying it alone

**Comment by TheGoldenAdmin** [comment]
Also it felt like some functions were dropped off. By that i mean shift clicking red cross in creative did nothing.

**Comment by Furgl** [comment]
I would assume it is an incompatibility issue with Bukkit, though I’m not able to test it myself right now.

**Comment by 2piradians** [comment]
Are you sure the versions of Bukkit and Forge you are using are compatible with each other?

**Comment by TheGoldenAdmin** [comment]
hold on ... i'll check

**Comment by TheGoldenAdmin** [comment]
filename of craftbukkit contains SNAPSHOT. That was only choice for 1.10.2. The 1.12.2 isn't SNAPSHOT but it behaves identicaly.

**Comment by 2piradians** [comment]
That doesn't really answer the question. Are Bukkit and Forge compatible in the first place? This post says  modded servers are not supported by Bukkit:

https://bukkit.org/threads/bukkit-and-forge.443630/

That was almost a year ago, but the question still needs to be answered, as that could be the issue.

**Comment by Furgl** [comment]
As far as I know and have heard, Forge can do anything that Bukkit can do and more, so why do you need Bukkit anyway?

**Comment by TheGoldenAdmin** [comment]
forge couldn't install and my cmd is messed up so no commands without gui and ram dedication didn't work. also the mods wasnt there

**Comment by 2piradians** [comment]
"Forge couldn't install"
Forge is needed for the mod. If you don't have it installed, that is your issue.

**Comment by TheGoldenAdmin** [comment]
sorry, meant forge server

**Comment by TheGoldenAdmin** [comment]
anyway do you know any server console for 1.10.2, 1.11.2 or 1.12.2 that have gui supporting ram dedication? (like bukkit)

**Comment by 2piradians** [comment]
But your server does have Forge installed if it can partially run the mod? 

I do not know any server consoles. Most servers I have hosted were hosted by myself on my own computer with easy access to the run commands.

**Comment by Furgl** [comment]
Forge servers support RAM dedication. I would recommend trying to figure out why you could not install Forge servers properly and why your cmd is messed up. As modded servers are not supported by Bukkit, we will not attempt to be compatible with it. I’m closing this issue, but if you need more help with Forge servers, we can always help
