### ISSUE TITLE
CRASH - Moira NPC Hero Ticking Entity

### ISSUE THREAD

**Issue by kd8lvt** [2piradians/Minewatch#6]
Moira crashes the server while getting direct look angle (by the look of the crash report.)
This occurs while she's attempting to look at a player to heal them. Instant crash when the affected player(s) log in, even after initial crash, with the same error.
Crashlog Gist: [crashlog](https://gist.github.com/kd8lvt/45f29a44e77f9a07108edd482b8e7b4d)

**Comment by Furgl** [comment]
Thank you for reporting this! This will be fixed for the next update. It only affects MC 1.10.2 servers, so I would recommend updating to 1.11.2 or 1.12.2 or staying in single player for a couple days until the update is out, if possible.
