### ISSUE TITLE
Minewatch Sombra

### ISSUE THREAD

**Issue by NerfThis123** [2piradians/Minewatch#8]
Love this new update but Sombra's  enemy hack is kinda weird you can see it trough walls and its purple and not red that's all I found right now.

**Comment by Furgl** [comment]
What do you mean by Sombra's enemy hack? Do you mean hacked health packs or hacked entities?

**Comment by NerfThis123** [comment]
Like when the enemy Sombra hacks a health pack you can see it through walls as if you hacked it or your teammate hacked it.

**Comment by Furgl** [comment]
If an enemy Sombra (a Sombra on a different team as you - not just a Sombra that's not on a team) hacks a health pack, you will not see it through walls. You will see a health pack through walls if it is hacked by a friendly/neutral Sombra (a Sombra on the same team or not on a team).

**Comment by NerfThis123** [comment]
o i guess i did not really play with all the mechanics sorry😅

**Comment by Furgl** [comment]
No problem, I may change it so that heroes not on teams are fully considered enemies too, to make it less confusing. But I'm glad you're enjoying the mod and thanks for your feedback!
